### PR TITLE
fix to work with 9.6 extension lwlock changes

### PR DESCRIPTION
**Pull request by poppuyo**
9.6 release of postgres removed LWLockAssign and RequestAddinLWLocks
https://www.postgresql.org/docs/9.6/static/release-9-6.html

From the link above:
Change the way that extensions allocate custom LWLocks (Amit Kapila, Robert Haas)
The RequestAddinLWLocks() function is removed, and replaced by RequestNamedLWLockTranche(). This allows better identification of custom LWLocks, and is less error-prone.

Thanks to isaiasanchez and rjuju for running into this at:
https://github.com/dalibo/pg_stat_kcache/issues/10 and the fix at https://github.com/dalibo/pg_stat_kcache/commit/58c34e75667d3f6786c2d6338c5317fb09dfe946

### CODE REVIEW

**Comment by poppuyo** [comment]
Hey mhagander,

I was looking into this extension (thanks for making it!) for a look into SSL statuses on a server I was tinkering on. That server was running postgresql 9.6, and I had to tweak your code to make it work with that server.

Figured I'd share back the investigation+changes so anyone else can just use this out of the box. :)

Best Regards,
Jason

**Comment by mhagander** [comment]
Hi!

PostgreSQL 9.5 already includes pg_stat_ssl which has all the information from this view. I sort of assumed this extension would be irrelevant on 9.5 and newer.

Do you have an actual use-case for this extension on 9.6?

**Comment by poppuyo** [comment]
Hello!

Well, that probably shows my lack of familiarity with postgresql.
`SELECT * FROM pg_stat_ssl;` works perfectly actually. I guess I just ran into pg_sslstatus because that was what came up most prominently in search. 

It was an interesting exercise all the same, but yes: pg_stat_ssl fits my needs. Feel free to drop/close this PR.
Thanks for your response!

Best Regards,
Jason

**Comment by mhagander** [comment]
Ok, thanks for confirming. I'll push an update to the README file to clarify the state.

**Pull request closed without merging**
